### ISSUE TITLE
Warning: variable "results" is unused in `check` block

### ISSUE THREAD

**Issue by ya-netgrp** [anyalir/behave#3]
Similar to "data" variable in `act` block https://github.com/anyalir/behave/issues/2
if inside `check` block there is no references to injected variable `results` it produces unused variable warning. 

However you can have a scenario when one ore more `check` blocks contain assertion against data from external state and don't need to access `results`. Another scenario when all your previous steps have been used only for side effects and there is nothing to access in `check` block.

**Comment by anyalir** [comment]
Hey, @ya-netgrp thanks for the feedback, I'm happy to work that in as soon as I'm able. ATM im in hospital and can't. You're welcome to fork in the meantime and send me a pr, but I won't be able to re-release until I get back from the clinic.

**Comment by anyalir** [comment]
Generally, I'm thinking to get around this all by making alternate forms of the macros that include `data` and `results` in the argument lists. If the variable is bound in the argument list passed to the macro, create the variable in scope and unquote it.

Alternatively there could also be a form of the macro where the user passes a lambda instead of a do block. That lambda then would receive either only Data, or data and results in case of a check step.

Again you're welcome to fork and build it like this, but if you have better ideas, I'd welcome them ofc.
